spring:
  datasource:
    username: ismail
    password: ismail
    url: jdbc:postgresql://localhost:5432/microservicedb
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update

#spring.profiles.active=dev
